import type { PosterPreset } from "@/features/presets/domain/types";

export const posterPresets: PosterPreset[] = [
  {
    id: "minimal-gallery",
    name: "Minimal Gallery",
    description: "Quiet print preset with generous type spacing.",
    layoutId: "print_a4_portrait",
    form: {
      theme: "midnight_blue",
      fontFamily: "Playfair Display",
      distance: "8500",
      showPosterText: true,
      showCoordinates: true,
      textScale: "100",
      includeCredits: true,
      includeLandcover: true,
      includeBuildings: true,
      includeWater: true,
      includeParks: true,
      includeAeroway: true,
      includeRail: true,
      includeRoads: true,
      includeRoadPath: true,
      includeRoadMinorLow: true,
      includeRoadOutline: true,
      showMarkers: true,
      showRoute: false,
    },
    exportSettings: {
      dpi: 300,
      marginMm: 0,
      bleedMm: 3,
      safeAreaMm: 5,
      cropMarks: true,
    },
  },
  {
    id: "travel-memory",
    name: "Travel Memory",
    description: "Readable city poster with markers and coordinates.",
    layoutId: "print_a5_portrait",
    form: {
      theme: "terracotta",
      fontFamily: "Lato",
      distance: "6200",
      showPosterText: true,
      showCoordinates: true,
      textScale: "104",
      includeCredits: false,
      includeLandcover: true,
      includeBuildings: true,
      includeWater: true,
      includeParks: true,
      includeAeroway: false,
      includeRail: true,
      includeRoads: true,
      includeRoadPath: true,
      includeRoadMinorLow: true,
      includeRoadOutline: true,
      showMarkers: true,
      showRoute: false,
    },
    exportSettings: {
      dpi: 300,
      marginMm: 0,
      bleedMm: 3,
      safeAreaMm: 5,
      cropMarks: true,
    },
  },
  {
    id: "city-coordinates",
    name: "City Coordinates",
    description: "Coordinate-led layout for a single place.",
    layoutId: "print_a4_portrait",
    form: {
      theme: "sage",
      fontFamily: "Montserrat",
      distance: "10000",
      showPosterText: true,
      showCoordinates: true,
      textScale: "96",
      includeCredits: false,
      includeLandcover: true,
      includeBuildings: false,
      includeWater: true,
      includeParks: true,
      includeAeroway: false,
      includeRail: false,
      includeRoads: true,
      includeRoadPath: true,
      includeRoadMinorLow: true,
      includeRoadOutline: true,
      showMarkers: false,
      showRoute: false,
    },
    exportSettings: {
      dpi: 300,
      marginMm: 0,
      bleedMm: 3,
      safeAreaMm: 5,
      cropMarks: true,
    },
  },
  {
    id: "gift-print",
    name: "Gift Print",
    description: "Warm print preset for a meaningful location.",
    layoutId: "print_a3_portrait",
    form: {
      theme: "coral",
      fontFamily: "Merriweather",
      distance: "7500",
      showPosterText: true,
      showCoordinates: true,
      textScale: "102",
      includeCredits: true,
      includeLandcover: true,
      includeBuildings: true,
      includeWater: true,
      includeParks: true,
      includeAeroway: false,
      includeRail: true,
      includeRoads: true,
      includeRoadPath: true,
      includeRoadMinorLow: true,
      includeRoadOutline: true,
      showMarkers: true,
      showRoute: false,
    },
    exportSettings: {
      dpi: 300,
      marginMm: 0,
      bleedMm: 3,
      safeAreaMm: 6,
      cropMarks: true,
    },
  },
  {
    id: "dark-architectural",
    name: "Dark Architectural",
    description: "High-contrast roads and buildings for dense cities.",
    layoutId: "print_letter_us_portrait",
    form: {
      theme: "neon",
      fontFamily: "Oswald",
      distance: "4800",
      showPosterText: true,
      showCoordinates: false,
      textScale: "98",
      includeCredits: false,
      includeLandcover: true,
      includeBuildings: true,
      includeWater: true,
      includeParks: false,
      includeAeroway: true,
      includeRail: true,
      includeRoads: true,
      includeRoadPath: true,
      includeRoadMinorLow: true,
      includeRoadOutline: true,
      showMarkers: false,
      showRoute: false,
    },
    exportSettings: {
      dpi: 300,
      marginMm: 0,
      bleedMm: 3,
      safeAreaMm: 5,
      cropMarks: true,
    },
  },
  {
    id: "race-route",
    name: "Race Route",
    description: "Route-forward poster using marker waypoints.",
    layoutId: "social_instagram_portrait",
    form: {
      theme: "ruby",
      fontFamily: "Bebas neue",
      distance: "12000",
      showPosterText: true,
      showCoordinates: false,
      textScale: "110",
      includeCredits: false,
      includeLandcover: true,
      includeBuildings: false,
      includeWater: true,
      includeParks: true,
      includeAeroway: false,
      includeRail: true,
      includeRoads: true,
      includeRoadPath: true,
      includeRoadMinorLow: true,
      includeRoadOutline: true,
      showMarkers: true,
      showRoute: true,
    },
    exportSettings: {
      dpi: 150,
      marginMm: 0,
      bleedMm: 0,
      safeAreaMm: 0,
      cropMarks: false,
    },
  },
];

export function getPosterPreset(presetId: string): PosterPreset | null {
  return posterPresets.find((preset) => preset.id === presetId) ?? null;
}
