import type { PosterPreset } from "@/features/presets/domain/types";

export const posterPresets: PosterPreset[] = [
  {
    id: "print-poster",
    name: "Print Poster",
    layoutId: "print_a4_portrait",
    form: {
      distance: "8500",
      showPosterText: true,
      showCoordinates: true,
      textScale: "100",
      includeCredits: true,
      includeLandcover: true,
      includeBuildings: true,
      includeWater: true,
      includeParks: true,
      includeAeroway: true,
      includeRail: true,
      includeRoads: true,
      includeRoadPath: true,
      includeRoadMinorLow: true,
      includeRoadOutline: true,
      showMarkers: true,
      showRoute: false,
    },
    exportSettings: {
      dpi: 300,
      marginMm: 0,
      bleedMm: 3,
      safeAreaMm: 5,
      cropMarks: true,
    },
  },
  {
    id: "mobile-wallpaper",
    name: "Mobile Wallpaper",
    layoutId: "wallpaper_iphone_15_pro",
    form: {
      distance: "7000",
      showPosterText: false,
      showCoordinates: false,
      textScale: "95",
      includeCredits: false,
      includeLandcover: true,
      includeBuildings: false,
      includeWater: true,
      includeParks: true,
      includeAeroway: false,
      includeRail: true,
      includeRoads: true,
      includeRoadPath: true,
      includeRoadMinorLow: false,
      includeRoadOutline: true,
      showMarkers: false,
      showRoute: false,
    },
    exportSettings: {
      dpi: 300,
      marginMm: 0,
      bleedMm: 0,
      safeAreaMm: 0,
      cropMarks: false,
    },
  },
  {
    id: "instagram-story",
    name: "Instagram Story",
    layoutId: "social_instagram_story_tiktok",
    form: {
      distance: "6500",
      showPosterText: true,
      showCoordinates: false,
      textScale: "105",
      includeCredits: false,
      includeLandcover: true,
      includeBuildings: false,
      includeWater: true,
      includeParks: true,
      includeAeroway: false,
      includeRail: false,
      includeRoads: true,
      includeRoadPath: true,
      includeRoadMinorLow: true,
      includeRoadOutline: false,
      showMarkers: true,
      showRoute: false,
    },
    exportSettings: {
      dpi: 150,
      marginMm: 0,
      bleedMm: 0,
      safeAreaMm: 0,
      cropMarks: false,
    },
  },
  {
    id: "desktop-wallpaper",
    name: "Desktop Wallpaper",
    layoutId: "wallpaper_desktop_4k",
    form: {
      distance: "11000",
      showPosterText: false,
      showCoordinates: false,
      textScale: "95",
      includeCredits: false,
      includeLandcover: true,
      includeBuildings: false,
      includeWater: true,
      includeParks: true,
      includeAeroway: false,
      includeRail: true,
      includeRoads: true,
      includeRoadPath: true,
      includeRoadMinorLow: true,
      includeRoadOutline: true,
      showMarkers: false,
      showRoute: false,
    },
    exportSettings: {
      dpi: 150,
      marginMm: 0,
      bleedMm: 0,
      safeAreaMm: 0,
      cropMarks: false,
    },
  },
];

export function getPosterPreset(presetId: string): PosterPreset | null {
  return posterPresets.find((preset) => preset.id === presetId) ?? null;
}
